### ISSUE TITLE
Obtaining a gravity time series formed by zeros

### ISSUE THREAD

**Issue by MiguelonGonzalez** [jkennedy-usgs/heavy-mirror#1]
I am using HEAVY to calculate the gravitational signal observed from a point within a very simplified hydrogeological model.
I have created and filled the requiered files (`nam `and `hvy`) properly, and executed the program successfully with the default options.
The `lst `and `out `files are created well within _Resultados_ folder, nevertheless, the created **gravity signal** is completeley **formed by zeroes**.

I do not know what could be happening. I attached all my files as a zip file ([Data.zip](https://github.com/jkennedy-usgs/heavy-mirror/files/11882540/Data.zip)), in case you could help.

For the hydrogeological model I am running **MODFLOW 2005** with**ModelMuse**, from a Windows 10 x64 bits machine.
Thank you very much in advance.

**Comment by jkennedy-usgs** [comment]
@MiguelonGonzalez I think it's because you're using real-world coordinates for your gravity station location in model.hvy, whereas Heavy requires coordinates relative to (0,0) at the lower-left corner of your model. Even though you may be working with real-world coordinates in ModelMuse, and the coordinates of the model corners are in the header in the .dis file, you will need to convert the locations in model.hvy to model coordinates (subtract the lower left coordinate from each gravity station location). 

I changed the station location to (1000, 1000, 2148) and got these results, which seem reasonable. I can look further if you think there's still an issue. 

 PRLBL               KPER    KSTP         TOTIM        d-uGAL
 C_BLANCA               1       1               1.000         0.000         0.000
 C_BLANCA               2       1               2.000         0.079         0.079
 C_BLANCA               3       1               3.000         0.154         0.154
 C_BLANCA               4       1               4.000         0.229         0.229
 C_BLANCA               5       1               5.000         0.308         0.308
 C_BLANCA               6       1               6.000         0.383         0.383
 C_BLANCA               7       1               7.000         0.461         0.461
 C_BLANCA               8       1               8.000         0.537         0.537
...
 C_BLANCA             138       1             138.000        10.423        10.423
 C_BLANCA             139       1             139.000        10.501        10.501
 C_BLANCA             140       1             140.000        10.576        10.576
 C_BLANCA             141       1             141.000        10.652        10.652
 C_BLANCA             142       1             142.000        10.727        10.727
 C_BLANCA             143       1             143.000        10.805        10.805
 C_BLANCA             144       1             144.000        10.881        10.881
 C_BLANCA             145       1             145.000        10.959        10.959
 C_BLANCA             146       1             146.000        11.034        11.034
 C_BLANCA             147       1             147.000        11.109        11.109
 C_BLANCA             148       1             148.000        11.185        11.185
 C_BLANCA             149       1             149.000        11.260        11.260

**Comment by MiguelonGonzalez** [comment]
Hello Jeff,
Thank you very much for your time. Exactly, it was an error of mine -I was introducing global coordinates and not relative ones.
I close the issue and open a new one with other concern. Thanks again!
